import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ChatBot from "./chat/components/chatbot";
import { AuthProvider } from "@/lib/AuthProvider";

import AuthModal from "./AuthModals";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Refrax",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script src="https://accounts.google.com/gsi/client" async></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark text-foreground bg-background`}
      >
        <AuthProvider>
          {children}
          <ChatBot /> {/* 👈 mounted globally */}
          <AuthModal /> {/* 👈 mounted globally */}
        </AuthProvider>
      </body>
    </html>
  );
}
